export const GET_POSTS_REQUEST = 'GET_POSTS_REQUESST';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_FAILED = 'GET_POSTS_FAILED';

export const GET_POST_BY_ID_REQUEST = 'GET_POST_BY_ID_REQUEST';
export const GET_POST_BY_ID_SUCCESS = 'GET_POST_BY_ID_SUCCESS';
export const GET_POST_BY_ID_FAILED = 'GET_POST_BY_ID_FAILED';

export const PUT_POST_REQUEST = 'PUT_POST_REQUEST';
export const PUT_POST_SUCCESS = 'PUT_POST_SUCCESS';
export const PUT_POST_FAILED = 'PUT_POST_FAILED';

export const POST_NEWPOST_REQUEST = 'POST_NEWPOST_REQUEST';
export const POST_NEWPOST_SUCCESS = 'POST_NEWPOST_SUCCESS';
export const POST_NEWPOST_FAILED = 'POST_NEWPOST_FAILED';

export const DELETE_POST_REQUEST = 'DELETE_POST_REQUEST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILED = 'DELETE_POST_FAILED';

export const GET_COMMENTS_REQUEST = 'GET_COMMENTS_REQUESST';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_FAILED = 'GET_COMMENTS_FAILED';